[changelog]
body = """
{% for group, commits in commits | group_by(attribute="group") %}
### {{ group }}
{% for commit in commits %}
- {% if commit.breaking %}**Breaking:** {% endif %}{{ commit.message | upper_first }}\
{% endfor %}
{% endfor %}
"""
trim = true

[git]
conventional_commits = true
filter_unconventional = true
filter_commits = true
protect_breaking_commits = true
tag_pattern = "v[0-9].*"
commit_parsers = [
    { message = "^feat", group = "Features" },
    { message = "^fix", group = "Fixes" },
]
