#!/usr/bin/env bash
set -euo pipefail

site=$(cd "$(dirname "$0")" && pwd)
docir=${DOCIR:-$site/../zig-out/bin/docir}
work=${WORK:-$site/../.zig-cache/samples}
out=$site/samples

mkdir -p "$work" "$out"
printf '# Samples\n\nReferences that docir generated from other projects, each from the commit named on its page. None of them is the official documentation of its project.\n\n| Project | Language | License |\n|---|---|---|\n' > "$out/index.md"
: > "$out/toc.yml"

count=$(jq length "$site/samples.json")
for index in $(seq 0 $((count - 1))); do
  field() { jq -r ".[$index].$1 // empty" "$site/samples.json"; }
  name=$(field name)
  title=$(field title)
  repository=$(field repository)
  commit=$(field commit)

  if [ -n "$(field toolchain)" ]; then
    root=$(dirname "$(zig env | sed -n 's/.*\.lib_dir = "\(.*\)",/\1/p')")
  else
    root=$work/$name
    if [ ! -d "$root/.git" ]; then
      git init -q "$root"
      git -C "$root" remote add origin "https://github.com/$repository"
    fi
    git -C "$root" fetch -q --depth 1 origin "$commit"
    git -C "$root" checkout -q FETCH_HEAD
  fi

  sources=$root/$(field directory)
  pages=$out/$name
  "$docir" read "$sources" --name "$name" --base "$sources" 2>/dev/null |
    "$docir" link 2>/dev/null |
    "$docir" write markdown --title "$title" --pages -o "$pages"

  {
    printf '# License of %s\n\n' "$title"
    printf 'These pages were generated by [docir](https://github.com/rael-g/docir) from [%s](https://github.com/%s) at `%s`. They reproduce declarations and documentation comments of that project, which are distributed under the license below.\n\n```text\n' "$repository" "$repository" "$commit"
    cat "$root/$(field license_file)"
    printf '\n```\n'
  } > "$pages/license.md"

  notice="Generated by docir from [$repository](https://github.com/$repository) at \`$commit\`. This is not the official documentation of $title. [License]($name/license.md)."
  sed -i "1a\\\\n${notice/$name\/license.md/license.md}" "$pages/index.md"
  printf -- '- name: License\n  href: license.md\n' >> "$pages/toc.yml"

  printf '| [%s](%s/index.md) | %s | [%s](%s/license.md) |\n' "$title" "$name" "$(field language)" "$(field license)" "$name" >> "$out/index.md"
  printf -- '- name: "%s"\n  href: %s/\n  homepage: %s/index.md\n' "$title" "$name" "$name" >> "$out/toc.yml"
done
